definitions:
  controller.PredictionRequest:
    properties:
      classes:
        items:
          type: string
        type: array
      context:
        items:
          type: number
        type: array
      model:
        type: string
      sample:
        type: boolean
    type: object
  controller.PredictionResponse:
    properties:
      prediction:
        type: number
    type: object
info:
  contact: {}
paths:
  /prediction:
    post:
      consumes:
      - application/json
      description: Predicts rewards for a given experiment.
      operationId: predict-experiment-rewards
      parameters:
      - description: Prediction Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.PredictionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.PredictionResponse'
      summary: Predict experiment rewards using ONNX models loaded in S3.
swagger: "2.0"
